"""Generate a best-effort VOSS flex-UNI config from an ERS L2 model (slice 3).

The old ERS is a plain 802.1Q switch; the new VOSS box is a fabric leaf. This
mirrors the field reference: each VLAN becomes an `i-sid <isid> elan` with
`c-vid <vlan> port <tagged ports>` and `untagged-traffic port <pvid ports>`,
each access port gets the flex-UNI boilerplate, and MLT/uplink handling is left
to the human. I-SIDs come from the resolver (fabric -> your decision -> REVIEW
placeholder). Old port numbers are kept as `1/N`. This is a GENERATED draft -
every assumption is annotated; it is not for blind paste.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from switch_migrator.config import Config
from switch_migrator.isid import IsidDecision, resolve
from switch_migrator.parsers.ers_config import ErsModel


@dataclass
class ErsGenerateResult:
    text: str
    decisions: list[IsidDecision] = field(default_factory=list)


def _compress(nums: list[int]) -> str:
    """[4,5,6,9,11,12] -> '1/4-1/6,1/9,1/11-1/12'."""
    nums = sorted(set(nums))
    if not nums:
        return ""
    runs: list[tuple[int, int]] = []
    start = prev = nums[0]
    for n in nums[1:]:
        if n == prev + 1:
            prev = n
            continue
        runs.append((start, prev))
        start = prev = n
    runs.append((start, prev))
    return ",".join(f"1/{a}" if a == b else f"1/{a}-1/{b}" for a, b in runs)


_HEADER = """\
# ==========================================================================
# GENERATED VOSS flex-UNI config from ERS - REVIEW, this is a DRAFT
# {src}
# Generated by switch-migrator. Target model assumed: flex-UNI fabric leaf.
#
# What was translated: VLAN -> I-SID (elan), tagged member -> c-vid,
#   PVID/untagged member -> untagged-traffic, access ports -> flex-UNI.
# Old ERS port numbers kept as 1/N.
#
# YOU MUST VERIFY:
#   - tagged vs untagged per port (c-vid vs untagged-traffic) against the
#     intended design - it is derived from the ERS 'tagging'/'pvid' config;
#   - the I-SID chosen for each VLAN (see REVIEW markers / the worksheet);
#   - uplink/MLT handling (see notes below) - those become the fabric uplink;
#   - everything NOT translated (QoS, EAP, rate-limit, MSTP details, ...) is a
#     separate step.
# ==========================================================================
"""


def _uplink_note(ers: ErsModel) -> list[str]:
    out = ["#", "# UPLINK / MLT notes (not generated as flex-UNI):"]
    if not ers.mlts:
        out.append("#   (no MLTs found)")
    for m in ers.mlts:
        members = ",".join(m.members) or "none"
        out.append(f"#   - MLT {m.mlt_id} \"{m.name}\" members {members}: if this is the "
                   f"uplink to the")
        out.append("#     core, it becomes the fabric uplink on the new box "
                   "(configure IS-IS on")
        out.append("#     the new uplink ports); if it is an access LAG, recreate "
                   "it as a flex-UNI MLT.")
    return out


def generate_voss_from_ers(ers: ErsModel, cfg: Config,
                           matched_by_vlan: dict[int, int] | None = None,
                           device_name: str = "") -> ErsGenerateResult:
    matched_by_vlan = matched_by_vlan or {}
    uplink: set[str] = set()
    for m in ers.mlts:
        uplink.update(m.members)

    decisions: list[IsidDecision] = []
    services: list[str] = []
    access_used: set[int] = set()

    for vid in sorted(ers.vlans):
        vlan = ers.vlans[vid]
        d = resolve(vid, vlan.name, cfg, matched_by_vlan.get(vid))
        decisions.append(d)
        if d.excluded:
            continue
        access = [p for p in vlan.members if p not in uplink]
        low = sorted(int(p) for p in access if int(p) <= 48)
        high = sorted(int(p) for p in access if int(p) > 48)
        if not low and not high:
            continue  # VLAN lives only on the uplink -> carried by the fabric

        untagged = [n for n in low if ers.ports.get(str(n)) and ers.ports[str(n)].pvid == vid]
        tagged = [n for n in low if n not in untagged]
        access_used.update(low)

        name = f' ({vlan.name})' if vlan.name else ""
        block: list[str] = []
        if d.needs_decision:
            cand = " / ".join(map(str, d.candidates)) or "(no offsets configured)"
            block.append(f"# [REVIEW] VLAN {vid}{name}: I-SID undecided - "
                         f"candidates {cand}. Set it, then uncomment:")
            prefix = "# "
        else:
            block.append(f"# VLAN {vid}{name} -> I-SID {d.isid} (from {d.source})")
            prefix = ""
        isid = d.isid if d.isid is not None else "<ISID>"
        block.append(f"{prefix}i-sid {isid} elan")
        if tagged:
            block.append(f"{prefix}c-vid {vid} port {_compress(tagged)}")
        if untagged:
            block.append(f"{prefix}untagged-traffic port {_compress(untagged)}")
        block.append(f"{prefix}exit")
        if high:
            block.append(f"# [REVIEW] VLAN {vid} also on ERS port(s) "
                         f"{','.join(map(str, high))} (SFP/high) - no 1/N "
                         f"equivalent, remap to the new hardware")
        services.append("\n".join(block))

    # flex-UNI access ports
    ports_out: list[str] = []
    for n in sorted(access_used):
        p = ers.ports.get(str(n))
        ports_out.append(f"interface GigabitEthernet 1/{n}")
        ports_out.append("default-vlan-id 0")
        if p and p.name:
            ports_out.append(f'name "{p.name}"')
        ports_out.append("flex-uni enable")
        ports_out.append("shutdown" if (p and p.shutdown) else "no shutdown")
        ports_out.append("slpp-guard enable timeout 0")
        ports_out.append("spanning-tree mstp edge-port true")
        ports_out.append("exit")

    src = f"Source switch : {device_name}" if device_name else "Source: ERS switch"
    parts = [_HEADER.format(src=src).rstrip()]
    parts += _uplink_note(ers)
    parts.append("\n#\n# I-SID SERVICE CONFIGURATION\n#")
    parts.append("\n".join(services) if services else "# (no services generated)")
    parts.append("\n#\n# PORT CONFIGURATION (flex-UNI access ports)\n#")
    parts.append("\n".join(ports_out) if ports_out else "# (no access ports)")
    text = "\n".join(parts).rstrip() + "\n"
    return ErsGenerateResult(text=text, decisions=decisions)
